spring:
  datasource:
    username: jonatan-prod
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/companies
    password: XGASXTYW634GFEYHY6gs
